version: '3'

tasks:
  default:
    desc: "Welcome! Run 'task --list' to see all available tasks and the order to run them."
    cmds:
      - task --list

  install:
    desc: "Step 1: Install all required dependencies."
    cmds:
      - pnpm install
      - cd playground-vite && npm install

  dev:prepare:
    desc: "Step 2: Prepare the Nuxt playground."
    cmds:
      - pnpm run dev:prepare

  dev:
    desc: "Step 3: Start the Nuxt playground server. This spins up the app so you can test the VSA module."
    cmds:
      - pnpm run dev

  dev:vite:
    desc: "Step 4: Start the Vite playground server."
    cmds:
      - cd playground-vite && npm run dev

  lint:
    desc: "Step 5: Lint your code."
    cmds:
      - pnpm run lint

  build:
    desc: "Step 6: Build the module."
    cmds:
      - pnpm run build

  dev:build:
    desc: "Step 7: Build the Nuxt playground application."
    cmds:
      - pnpm run dev:build
