<script server>
export async function GET(event) {
  // Using standard Web APIs to return an HTML file!
  // This is completely agnostic and works in any environment (Node, Deno, Edge, etc.)
  
  const content = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SEO Friendly HTML Example</title>
  <meta name="description" content="This is an SEO friendly HTML page generated by a VSA API endpoint.">
</head>
<body>
  <header>
    <h1>Welcome to VSA</h1>
  </header>
  <main>
    <article>
      <h2>About This Page</h2>
      <p>This is a plain HTML document returned directly from the API endpoint. It includes proper semantic tags and meta descriptions, making it friendly for search engine optimization (SEO).</p>
    </article>
  </main>
</body>
</html>`
  
  return new Response(content, {
    status: 200,
    headers: {
      'Content-Type': 'text/html; charset=utf-8'
    }
  })
}
</script>
