<script server>
export async function GET(event) {
  // Using standard Web APIs to return a text file!
  // This is completely agnostic and works in any environment (Node, Deno, Edge, etc.)
  
  const content = "Hello! This is a plain text file generated by a VSA API endpoint using standard Web Response."
  
  return new Response(content, {
    status: 200,
    headers: {
      'Content-Type': 'text/plain',
      'Content-Disposition': 'attachment; filename="hello.txt"'
    }
  })
}
</script>
