<script server>
export async function GET(event) {
  // Using standard Web APIs to return an XML file!
  // This is completely agnostic and works in any environment (Node, Deno, Edge, etc.)
  
  const content = `<?xml version="1.0" encoding="UTF-8"?>
<note>
  <to>User</to>
  <from>VSA</from>
  <heading>Hello</heading>
  <body>This is an XML file generated by a VSA API endpoint!</body>
</note>`
  
  return new Response(content, {
    status: 200,
    headers: {
      'Content-Type': 'application/xml',
      'Content-Disposition': 'attachment; filename="data.xml"'
    }
  })
}
</script>
